### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by cmjlee3** [cmjlee3/project3#1]
Need help saving markers to database so that they reappear when page is reloaded

Identify the code snippet that is giving you an issue:
![screen shot 2016-12-13 at 12 12 04 pm](https://cloud.githubusercontent.com/assets/20479988/21150551/696f52f8-c12d-11e6-8277-0afea8e5520d.png)

Tell us 3 things that you tried in order to solve the issue:
-tried to create a from to save the data
-attempted at saving to mongo
-went through a few tutorials but no luck so far..

@jasonseminara, @gittheking, @rapala61

**Comment by cmjlee3** [comment]
@trevorpreston

**Comment by trevorpreston** [comment]
Not queued until you fill out everything we need for this issue.

**Comment by rapala61** [comment]
@trevorpreston is right, please update the issue accordingly!

**Comment by gittheking** [comment]
@cmjlee3, you should be able to save markers in an object and then use a fetch to post them to a database after you create a new marker like:
```
const markerInfo = {
  position: results[0].geometry.location,
  title: sites[0],
  zIndex: sites[3],
  html: sites[4]
}

fetch('/api/user/markers', {
  method: 'POST',
  type: 'application/json',
  body: markerInfo
})
.catch(err => console.log(err));
```

**Comment by cmjlee3** [comment]
Awesome, working on the route/model now, thank's for the starting point @gittheking

**Comment by cmjlee3** [comment]
Hello! 

I'm working on my fetch to grab all the stored markers in order to render them when the map loads, here's what I have so far:

google script initialize function:
![screen shot 2016-12-14 at 10 36 55 am](https://cloud.githubusercontent.com/assets/20479988/21188395/48bccf4c-c1e9-11e6-85ca-4e002ccf28fb.png)

model (the console.logs aren't logging):
![screen shot 2016-12-14 at 10 37 44 am](https://cloud.githubusercontent.com/assets/20479988/21188426/61d04374-c1e9-11e6-82ca-802b1c690b65.png)

route (the bottom one is the route the fetch in the script should be hitting. I separated it from the route right above it bc i was getting some funky error):
![screen shot 2016-12-14 at 10 38 29 am](https://cloud.githubusercontent.com/assets/20479988/21188456/7d2072e8-c1e9-11e6-9a29-82e415e990a0.png)

Perhaps there's something wrong with my fetch, but also confused as to why the model function isn't being reached. 

@rapala61
@gittheking

**Comment by trevorpreston** [comment]
queued.

**Comment by cmjlee3** [comment]
Thank you!!!!!
